### ISSUE TITLE
Undefined list indices in polarization_compensation.py

### ISSUE THREAD

**Issue by JunHerng** [s-fifteen-instruments/QKDServer#6]
Not an issue at the moment as the function containing the indices is not in use.

Line 129-130:

wrong_coin=sum([l1[i]+ l2[i] + l3[i] +l4[i] for i in wrong_coinc_index])
good_coin=sum([l1[i]+ l2[i] + l3[i] +l4[i] for i in good_coinc_index])

wrong_coinc_index and good_coinc_index are not defined. Is the intended index len(l1) or similar? Are the good and wrong indices different?

**Comment by syed82ab** [comment]
The indices are now defined here in `service_T3()` 

https://github.com/s-fifteen-instruments/QKDServer/blob/f8d86efd19f115e84ec4776de1a52df6cf5c84b2/S15qkd/utils.py#L351-L352
