### ISSUE TITLE
Process.kill does not close pipes when process terminates/killed

### ISSUE THREAD

**Issue by pyuxiang** [s-fifteen-instruments/QKDServer#9]
Issue initially identified by Syed. Process class starts a child process which opens pipes according to inherited file descriptors, but does not close the pipes when this child process is closed.

Last recalled according to documentation, opened files and pipes should be terminated by the process itself, while the initial file descriptors created in the Process class is also properly handled as below: 

https://github.com/s-fifteen-instruments/QKDServer/blob/60d33f55968d7c7fcb998020efb0b19f9e19985f/S15qkd/utils.py#L125-L127

Reproduction steps yet to be specified.

**Comment by syed82ab** [comment]
Pipes are opened blocking for reading. When a read occurs with no data, it will be blocked.
Solved with flushing of pipes with a newline termination and also opening the pipe without blocking
https://github.com/s-fifteen-instruments/QKDServer/blob/348f1c548b16ec3fdb912da7f7e95469677a0f74/S15qkd/utils.py#L227C1-L230C1
https://github.com/s-fifteen-instruments/QKDServer/blob/348f1c548b16ec3fdb912da7f7e95469677a0f74/S15qkd/utils.py#L297
